### ISSUE TITLE
`Semicolon or block is expected` CSS error when using `@apply` with any directive functions, when missing `svelte-windicss-preprocess`

### ISSUE THREAD

**Issue by V-ed** [windicss/vite-plugin-windicss#98]
**Describe the bug**

![image](https://user-images.githubusercontent.com/16652915/111843161-136a1e80-88d7-11eb-84d2-c76d5689459b.png)

---

### _EDIT_ : Please read this if you come by this issue for the first time

If you also have the error `Semicolon or block is expected`, please try the steps in [this comment below](https://github.com/windicss/vite-plugin-windicss/issues/98#issuecomment-804222608), which adds a potential temporary fix for svelte to stop spewing out errors, both in vscode and when trying to open your site.

The remaining issue with this is the fact that css seems to be outputted in a weird way, especially when using third party packages (Routify in my case), so some ways of working with WindiCSS aren't fully functional.

If you want to take part of the journey where I pull my hair out, you can keep reading below, otherwise try the linked comment above and keep an eye out for an official statement on the resolution of this issue!

---

I've been pulling my hair out in these past few hours while trying to fix this issue.

While I know that it comes from svelte, I have successfully removed it by using `svelte-windicss-preprocess`, which prevents errors and actually compiles to something in the end. However, when using `svelte-windicss-preprocess` at the same time as `vite-plugin-windicss`, it seems like the css generation isn't ideal, as the directives aren't working :

![image](https://user-images.githubusercontent.com/16652915/111842887-8c1cab00-88d6-11eb-9323-141d65195a3f.png)

([Tailwind UI's default Navbar](https://tailwindui.com/components/application-ui/navigation/navbars), which shouldn't show the mobile hamburger menu in desktop mode. this doesn't happen when the `@apply` css is commented out and `svelte-windicss-preprocess` is deactivated, as shown below)

![image](https://user-images.githubusercontent.com/16652915/111842928-9d65b780-88d6-11eb-8be6-36b82e2055bd.png)

**Minimal Reproductions**

**Versions**
- vite-plugin-windicss: 0.9.4
- vite: 2.1.2
- framework(vue/react/svelte/etc): svelte

- svelte-windicss-preprocess: 3.0.2

**Additonal Context**

I'm probably simply missing a configuration option, but I searched through a lot of windicss's repos and different packages, and most issues that tackle this doesn't seem to be containing a fix that worked for me.

I could provide a repo if desired.

**Comment by shiftgeist** [comment]
Having the same issue with svelte: The compile doesn't let is pass.

![image](https://user-images.githubusercontent.com/30648730/111890532-700a2e00-89ea-11eb-91bd-d73655a07a72.png)

![image](https://user-images.githubusercontent.com/30648730/111890534-78faff80-89ea-11eb-9a91-41c6a0e0bfbd.png)

One solution:

![image](https://user-images.githubusercontent.com/30648730/111890548-aa73cb00-89ea-11eb-96a6-ed73bca94e7b.png)

**Comment by antfu** [comment]
I am not an expert on svelte, can you share with me a minimal reproduction so I can have a look? Thnks.

**Comment by V-ed** [comment]
Sure thing : https://github.com/V-ed/windicss-svelte-repro

The master branch contains a semi-stripped down version of my repository that uses routify (I could strip it down further if required), but basically, if you open `src/pages/_components/Item.svelte`, this is where I put the code in error (https://github.com/V-ed/windicss-svelte-repro/blob/27ae779a5d8af800a392f5acec916001e1b5df86/src/pages/_components/Item.svelte#L30). This error happens both when you see the code in vscode and when you run vite with `npm run dev` (vite has no error, but when viewing the page an error overlay pops up).

In the branch `fix-errors-but-bad-compile`, I added `svelte-windicss-preprocess`, so vscode shows no more error (the Svelte's vscode extension picks up the `svelte.config.js` file correctly), but when you run the app, you'll see that most of the styling is actually applied (buttons are rond, colored, etc) but the look of the app is different, I think because some directive utilities (`sm:`, `md:`, etc) are not parsed correctly (but some are, such as the hover: on buttons or links, etc)

I don't exactly know how to describe what's missing in the compilation, maybe you'll know better than me, but I think it might be because there's two windi compiler acting at the same time and that may be the reason is both works and doesn't at the same time...

Thanks for looking into this!

**Comment by V-ed** [comment]
I have made another repo using [this template](https://github.com/reepolee/svelte-vite-windi) : https://github.com/V-ed/windicss-svelte-preprocess-error/tree/vite-plugin-windicss with the `vite-plugin-windicss` branch and while it seems to work on this one, it might be too small yet to find inconsistencies - I'll try adding few components to see if this issue happens in this new setup or not, I'll report back here.

**Comment by V-ed** [comment]
The takeaway I see is that while `vite-plugin-windicss` does help with configuring vite and windicss together, the dependency to `svelte-windicss-preprocess` is still required for svelte projects.

If this is the mentality that this plugin goes with, Ibelieve it should be mentionned in the `vite-plugin-windicss`'s steps. Here's an example of what I'm thinking could be in the WindiCSS docs :
```
While this plugin allows you to quickly use WindiCSS in Vite, you may need to add preprocessing to your own framework's files to make sure that WindiCSS is also compatible with it.
```

**Comment by shiftgeist** [comment]
My take on an minimal reproduction: [App.svelte#L29](https://github.com/shiftgeist/vite-svelte-ts-windicss/blob/vite-plugin-windicss-98/src/App.svelte#L29).

It breaks on (eg) `sm:p-2` and `sm:(p-2 m-2)`

**Comment by V-ed** [comment]
> My take on an minimal reproduction: [App.svelte#L29](https://github.com/shiftgeist/vite-svelte-ts-windicss/blob/vite-plugin-windicss-98/src/App.svelte?rgh-link-date=2021-03-22T16%3A38%3A26Z#L29).
> 
> It breaks on (eg) `sm:p-2` and `sm:(p-2 m-2)` with the error message `[plugin:vite-plugin-svelte] Semicolon or block is expected`.

You should try on your side to add windicss preprocess to svelte :

Add a `svelte.config.js`, with this content :

```js
const { preprocess: windicssPreprocess } = require('svelte-windicss-preprocess');

function createSveltePreprocessHandling() {
	return [
		windicssPreprocess({
			compile: false,
		}),
	];
}

module.exports = {
	preprocess: createSveltePreprocessHandling(),
	createSveltePreprocessHandling,
};
```

(add the missing packages if required)

Then, in your vite.config.ts` :

```ts
import { createSveltePreprocessHandling } from './svelte.config';
...
  plugins: [
    ...
    WindiCSS(),
    svelte({
      preprocess: createSveltePreprocessHandling()
    }),
	...
  ]
```

If you are using vscode with the svelte extension, don't forget to reload the svelte language (`Svelte: Restart Language Server`) or your vscode window

**Comment by shiftgeist** [comment]
Thanks for the suggestion @V-ed. I updated the [svelte](https://github.com/shiftgeist/vite-svelte-ts-windicss/commit/a70897168f2bfa9dfbc6d7fc2bf9c568e079e427#diff-6317e218ea40a2a9b47af98e100e81c06f9c0abff66737e6ca06ec4b29402242) and [vite](https://github.com/shiftgeist/vite-svelte-ts-windicss/commit/a70897168f2bfa9dfbc6d7fc2bf9c568e079e427#diff-58e6f63d87181b1c6a8cb6e5f1691df04aa32854456efcd52ca71c8541375d26) configs. The compiler no longer throws any errors.

I changed the [implementation](https://github.com/shiftgeist/vite-svelte-ts-windicss/commit/a70897168f2bfa9dfbc6d7fc2bf9c568e079e427#diff-d68daa8b73cec8e4419759802bbd91e9f87f8ee02f25cdb1d12582ef6de848db): I couldn't get `@apply dark:bg-black` [2] to work. However i got it working with `dark="bg-black"` (in the template [1]). But the svelte vscode extension throws an error: [3], but that doesn't have any impact on the compiler (with reload too).

\[1/2]: Screenshot:

![image](https://user-images.githubusercontent.com/30648730/112035030-74942b00-8b3f-11eb-82ed-f210f5f5263a.png)

\[3]: Error message from `svelte.svelte-vscode`:

![image](https://user-images.githubusercontent.com/30648730/112035708-1ca9f400-8b40-11eb-964a-c1c87c4fb8ba.png)

**Comment by V-ed** [comment]
Yeah, when looking at different issues, many pointed out that we should disable svelte's extension diagnostics for css : `"svelte.plugin.css.diagnostics.enable": false,` , and use `stylelint` if we wanted css diagnostics, maybe that could fix the other issue about `dark:`.

Tried it myself on a quick elem and got an error at the end of my `</style>` tag :

![image](https://user-images.githubusercontent.com/16652915/112036632-40a50f80-8b17-11eb-8761-4ba5df98ce34.png)

![image](https://user-images.githubusercontent.com/16652915/112036600-36831100-8b17-11eb-925a-49790c58cce3.png)

(also, I don't have hover information about `dark:bg-black` but that's probably an issue with `WindiCSS Intellisense`, not picking up directive functions at the end of `@apply` statements, which is outside the scope of this current issue)

**Comment by shiftgeist** [comment]
> ![image](https://user-images.githubusercontent.com/16652915/112036632-40a50f80-8b17-11eb-8761-4ba5df98ce34.png)

Does `sm:(w-auto)` work for you?

**Comment by V-ed** [comment]
> Does `sm:(w-auto)` work for you?

Yes, in my second repo that works :
![image](https://user-images.githubusercontent.com/16652915/112038437-35eb7a00-8b19-11eb-9afb-dd1ab8b5f056.png)
(images scale up when on `md`, but not on mobile)

> edit: `"svelte.plugin.css.diagnostics.enable": false,` was already disabled for my `vite-svelte-ts-windicss` project.

unfortunate, you probably have `"css.validate": false` too then, but as I do have an error myself with the dark directive, this doesn't really help :/

**Comment by antfu** [comment]
I have been able to have to time to go through your discussions and try out your repro. But maybe you can try with

```ts
WindiCSS({
  transformCSS: 'pre'
})
```

First to see if it works. Before I get back to them.

Otherwise, a minimal repro will be the best.

**Comment by V-ed** [comment]
Unfortunately no, adding `transformCSS: 'pre'` to the VitePluginWindicss plugin options doesn't work :(

**Comment by V-ed** [comment]
Update : Right after adding Routify in my barebone repo, I started seeing the problem I'm describing here.

For some reason, I haven't thought about looking at the classes added to the element, and what is currently being applied... and I made a smal but interesting discovery :

![image](https://user-images.githubusercontent.com/16652915/112056827-df893600-8b2e-11eb-9a89-faf3bc345270.png)

What tells the mobile menu button to hide itself on screens larger than `sm` is this piece of code :

![image](https://user-images.githubusercontent.com/16652915/112056908-fcbe0480-8b2e-11eb-8188-0b47a27d2d6d.png)

`class="[...] flex items-center sm:hidden"`

For some reason, when I pass it through Routify first, the `sm:hidden` class is being overridden by `flex`, which allows him to be set accordingly.

---

## Now comes the fun part

... I can actually fix the weird class ordering using `@apply`.

```diff
- <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
+ <div class="absolute inset-y-0 left-0 mobile-menu">

...

+ <style>
+	.mobile-menu {
+		@apply flex items-center sm:hidden;
+	}
+</style>
```

<table>
<tr>
	<td><i>Before</i> adding the <code>@apply</code>
	<td><b><i>After</i></b> adding the <code>@apply</code>
<tr>
	<td><img src="https://user-images.githubusercontent.com/16652915/112057771-1a3f9e00-8b30-11eb-9eca-e2df658eb112.png" />
	<td><img src="https://user-images.githubusercontent.com/16652915/112057721-0b58eb80-8b30-11eb-9c29-a1ed3b8bbb09.png" />
</table>

This works because svelte, with the combination of WindiCSS, create a single class ( which contains the `flex`, but also the same class with

In a repo without routify setup, I have this :

![image](https://user-images.githubusercontent.com/16652915/112058789-663f1280-8b31-11eb-9064-55de7079b724.png)

![image](https://user-images.githubusercontent.com/16652915/112058768-60493180-8b31-11eb-9f3e-b8c950c5d07c.png)

While the classes are in the div directly, without @apply, their specificity seems to be better handled (`sm:hidden` has a narrower specificity than `flex`, so it's the one to get applied).

---

## What to do next

I think I'll need to investigate some more how Routify handles pages and how CSS handles the specificities of its selectors. This is a weird issue, in the fact that the classes are correctly added, but the specificity seems to be lost.

Question : I have no idea how does tailwindcss (and therefore Windicss) handles specificity for css classes - could this be the reason, and if so, do you think there's any fix for this?

I could make it work with routify using classes and lots of `@apply`, but I now lose the speed of simply adding a tailwind class to the element I want to style, which is a bit deceiving.

Also, I could change the title of this issue, but at the same time, I believe that there should be a mention in the doc about this vite plugin that mentions it doesn't fully replace framework preprocessors - or this is the case and my issue is an actual bug of the plugin? I can't tell between the two.

**Comment by V-ed** [comment]
Update : adding `important: true` to the tailwind / windicss configs helps with a lot of directives messing up the specificity...

I still have some issues with conditional classes but I'll keep trying to find ways around that

... I don't see exactly how adding `!important` to all classes (with the `important` option) fixes this issues, but css is a mystery yet to be unveiled. :)

I'll look some more if there's a universal-ish fix so that everything works with routify, I'll keep this thread updated.

**Comment by TheSimpleZ** [comment]
I'm experiencing the same issue. [Here's a minimal repro](https://github.com/TheSimpleZ/svelte-windi-repro) using [this svite template](https://github.com/svitejs/svite/tree/main/packages/templates/windicss)

It's a simple svelte app with no extra packages. You can see the changes I've made in the 2 commits that are on master. Basically, I've only upgraded all packages and added a style to make an element change background color on hover using @apply.

You can see the error by running `npm i` then `npm run dev`.

```
12:05:07 AM [vite] Internal server error: Semicolon or block is expected
  Plugin: vite-plugin-svelte
  File: /home/zrean/projects/svelte-windi-repro/src/App.svelte
  10: <style>
  11:   h1 {
  12:     @apply text-svelte-500 p-2 bg-green-200 hover:bg-red-200;
                                                       ^
  13:   }
  14: 
      at error (/home/zrean/projects/svelte-windi-repro/node_modules/svelte/compiler.js:16752:20)
      at Parser$1.error (/home/zrean/projects/svelte-windi-repro/node_modules/svelte/compiler.js:16828:10)
      at Object.read_style [as read] (/home/zrean/projects/svelte-windi-repro/node_modules/svelte/compiler.js:13141:21)
      at tag (/home/zrean/projects/svelte-windi-repro/node_modules/svelte/compiler.js:15887:34)
      at new Parser$1 (/home/zrean/projects/svelte-windi-repro/node_modules/svelte/compiler.js:16787:22)
      at parse$3 (/home/zrean/projects/svelte-windi-repro/node_modules/svelte/compiler.js:16919:21)
      at compile (/home/zrean/projects/svelte-windi-repro/node_modules/svelte/compiler.js:29918:18)
      at compileSvelte (/home/zrean/projects/svelte-windi-repro/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:291:48)
      at TransformContext.transform (/home/zrean/projects/svelte-windi-repro/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:679:33)
      at Object.transform (/home/zrean/projects/svelte-windi-repro/node_modules/vite/dist/node/chunks/dep-efe32886.js:43649:53)
```

**Comment by V-ed** [comment]
I have added an edit to the origin issue that mentions the fix of using `svelte-windicss-preprocess`, in the hopes that if someone else sees this issue, they can try to fix it while an official response is made.

@antfu, I think this issue can be closed since most of my issue now is about third party libraries, which I guess I could create another issue for (this one was mainly about `Semicolon or block is excepted`).

If you'd prefer to keep it open until an official fix is made (either mentionning in the docs to use the preprocessor of each respective frameworks as well as this, or if this is an exception for svelte, etc, _or_ tweaking `vite-plugin-windicss` to handle Semicolon errors more gracefully), I'm leaving this choice to you / other contributors :)

**Comment by antfu** [comment]
Did a quick investigation, it looks like the Svelte plugin does not emit the raw CSS content for other processors to transform before goes to Svelte's own css compiler. And that's possibly why it does not understand the `@apply` syntax. I will keep work with @dominikg to see if we can find a solution for this.

**Comment by antfu** [comment]
Should be fixed after https://github.com/sveltejs/vite-plugin-svelte/pull/13 got released.

**Comment by V-ed** [comment]
> Should be fixed after https://github.com/sveltejs/vite-plugin-svelte/pull/13 got released.

Awesome!

One thing that I'm wondering however is that while `vite-plugin-svelte` should in theory be compatible with windicss (and other plugins that needs it, that looks like a nice PR :) ), will vscode still throw an error, but it won't show in the browser? will we still need to add a preprocessor to Svelte (`svelte.config.js`) ourself?

Thanks for the quick fix, it is very much appreciated!

**Comment by antfu** [comment]
It's released https://github.com/sveltejs/vite-plugin-svelte/blob/main/packages/vite-plugin-svelte/CHANGELOG.md#100-next6

**Comment by HenrijsS** [comment]
Is `svelte-windicss-preprocess` required again?

It threw me this error on the `version "1.0.0-next.385"`.
Installing and adding the preprocess fixed it.

**Comment by dominikg** [comment]
still works https://stackblitz.com/edit/sveltejs-kit-template-default-nr1wjy?file=src/routes/index.svelte
see also https://github.com/sveltejs/vite-plugin-svelte/tree/main/packages/playground/windicss
